version: 2

jobs:
    test:
        docker:
            - image: fkrull/multi-python
        steps:
            - checkout
            - run:
                name: Test
                command: 'tox'
            - run: 
                name: Upload code coverage
                command: 'bash <(curl -s https://codecov.io/bash)'

workflows:
    version: 2
    test:
        jobs:
            - test

